---
- hosts: all

  become: true
  tasks:
    - name: update yum packages
      yum:
        name: 
          - nano
          - wget
          - unzip
          - Docker
        state: latest
        update_cache: true
