---
- hosts: all
  
  become: true
  host myip.opendns.com resolver1.opendns.com | grep myip
  tasks:
    - name: update yum packages
      yum:
        name: 
          - nano
          - wget
          - unzip
          - Docker
        state: latest
        update_cache: true
